### ISSUE TITLE
Push notifications don't disappear if there is more than one

### ISSUE THREAD

**Issue by puehringer** [datavisyn/tdp_core#311]
* Google Chrome Version 77.0.3865.90

### Steps to reproduce

1. Create more than one push notification (e. g by saving something, create an error, ....) within a short period of time.
 

### Observed behavior
* Push notifications are permanently visible.

### Expected behavior
*  Push notifications disappear after a certain amount of time

![Push-Noti1](https://user-images.githubusercontent.com/45141967/67862235-0b62e080-fb22-11e9-92c0-8d11ed302187.png)
![Push-Noti2](https://user-images.githubusercontent.com/45141967/67862273-1cabed00-fb22-11e9-8bc5-e2eca7fea813.png)

**Comment by thinkh** [comment]
I think it is not a good idea that **all** push notifications disappear after a certain time, because they might contain some link when sharing a session that the user might want to open later.

![grafik](https://user-images.githubusercontent.com/5851088/75253955-d3be2980-57df-11ea-861e-586f2a066a31.png)

**Comment by lehnerchristian** [comment]
by default a push notification does not disappear: https://github.com/datavisyn/tdp_core/blob/develop/src/notifications.ts#L33-L35 (by default `autoHideInMs` is -1)

there is only a non-configurable delay of 5 seconds if you use https://github.com/datavisyn/tdp_core/blob/develop/src/notifications.ts#L39-L41, which is not ideal
