### ISSUE TITLE
Molecule Column/Renderer for Lineup

### ISSUE THREAD

**Issue by puehringer** [datavisyn/tdp_core#741]
## Summary

We need a column/renderer for molecules. This should build upon https://github.com/datavisyn/tdp_core/issues/740. 

- [x] Renders image of molecule with given SMILES
- [ ] Optional: Render in SMILES in bulk with debounced fetch
- [x] Renders maximum common substructure (MCS) for aggregated SMILES
- [x] Optional: Renders [similarity map](https://jcheminf.biomedcentral.com/articles/10.1186/1758-2946-5-43) for exactly two aggregated SMILES
- [x] Allows substructure & SMARTS queries via the filter interface
- [x] Shows substructure matches in the images if filtered

For reference, see ChEmbVis: https://github.com/puehringer/ChEmbVis/tree/main/client/src/components/ranking

**Comment by puehringer** [comment]
@thinkh Ideally, one would be able to write SMILES/SMARTS into the textarea, a request is sent with the current set of structures + the query, and the resulting true/false map is used as filter. In the future, a chemical drawing addon might be used instead of the textarea. 
I.e. ideally we would have a custom filter menu there, as otherwise things become messy.

**Comment by thinkh** [comment]
Thanks for the explanation. If I'm not mistaken, then explanation would still need another API endpoint to generate the filter map. 

Furthermore, I agree that we will need a custom filter dialog then.

I'm not sure if we can implement all of this until the demo, but we'll try. Otherwise I will open a follow-up issue.
